### ISSUE TITLE
[Issue] getting an error when installing NexoPos (database setup)

### ISSUE THREAD

**Issue by leonidas79** [Blair2004/NexoPOS#1206] opened 2022-12-13 11:27 UTC
**The error**
when installing NexoPos , the  installation wizard that shows the database configuration page , i filled all infos and when i hit 'Save DataBase' i got an error on the console : 

`vendor.js?id=55a43eead10988a220735a7e6c14f715:2 ReferenceError: nsHttpClient is not defined`

**Environment:**
 - NexoPOS 4.x 4.8.8
 - Php 8.1.12
 - MySQL 5.7.26
 - Composer 2.4.4

**Comment by Blair2004** [comment] 2022-12-15 01:25
Hi,
Are you installing locally or remotely ?

**Comment by leonidas79** [comment] 2022-12-15 10:21
locally

**Comment by Blair2004** [comment] 2022-12-15 10:36
If you're a customer (means you've purchased a license), please get in touch with us at contact@nexopos.com. We'll take a look at your installation.

**Comment by leonidas79** [comment] 2022-12-15 10:43
hi , i am using the free version.

**Comment by Blair2004** [comment] 2022-12-15 18:08
Alright, can you share a video that will allow us understand what's going on ? The error might be caused by something else, maybe the server returns an error when you try to submit the database details. I'll will be helpful to include response of the server while submitting.

**Comment by leonidas79** [comment] 2022-12-16 09:47
Hi
here is the errors from the console

bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1 Uncaught TypeError: Cannot read properties of undefined (reading 'headers')
    at 7700 (bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:5283)
    at n (manifest.js?id=05687c4416821174765a9620f9e50c4f:1:147)
    at bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:26019
    at n.O (manifest.js?id=05687c4416821174765a9620f9e50c4f:1:429)
    at bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:26039
    at o (manifest.js?id=05687c4416821174765a9620f9e50c4f:1:3794)
    at bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:63
7700 @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1
n @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1
(anonymous) @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1
n.O @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1
(anonymous) @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1
o @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1
(anonymous) @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1
lang-loader.min.js:1          GET http://127.0.0.1:8000/lang/en.json 404 (Not Found)
(anonymous) @ lang-loader.min.js:1
value @ lang-loader.min.js:1
value @ lang-loader.min.js:1
t @ lang-loader.min.js:1
3680 @ lang-loader.min.js:1
n @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1
(anonymous) @ lang-loader.min.js:1
o @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1
(anonymous) @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1
(anonymous) @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1
(anonymous) @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1
setup.min.js:1 (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}]
setup.min.js:1 (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}]
setup.min.js:1 {…}
setup.min.js:1 {…}
setup.min.js:1 {…}
setup.min.js:1 {…}
setup.min.js:1 {…}
setup.min.js:1 {…}
setup.min.js:1 {…}
vendor.js?id=55a43eead10988a220735a7e6c14f715:2 ReferenceError: nsHttpClient is not defined
    at s.checkDatabase (setup.min.js:1:133221)
    at s.validate (setup.min.js:1:132839)
    at click (setup.min.js:1:135511)
    at $n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2556498)
    at s.n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2544141)
    at $n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2556498)
    at t.$emit (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2576374)
    at click (eval at Ul (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2637360), <anonymous>:3:124)
    at $n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2556498)
    at HTMLDivElement.n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2544141)

**Comment by Blair2004** [comment] 2023-01-05 22:21
It appears this issue persist on recent NexoPOS release. We're reopening for investigation.

**Comment by DoM1niC** [comment] 2023-01-07 02:52
Same Problem with Stable and current Master Branch

**Comment by chapdel** [comment] 2023-01-10 07:12
Same bugs. I'm waiting for the answer from the support since more than 4 days.

**Comment by Boors96** [comment] 2023-01-10 19:49
Same bugs here, I am installing locally

**Comment by Blair2004** [comment] 2023-01-10 21:47
Hi,

Please one of you having that issue, consider either:
- sending a zip of the project you downloaded
- tell exactly which version you downloaded (a link could be useful)

You might also need to mention whether is master, v4.8.x or v5.x

**Comment by Boors96** [comment] 2023-01-11 05:21
This is the link for the project:
https://github.com/Blair2004/NexoPOS.git
Version: 4.8.12

**Comment by Blair2004** [comment] 2023-01-11 13:07
Should be fixed with the latest release 4.8.13

**Closed by Blair2004** 2023-01-11 13:07 UTC
Labels: unreproducible

**Comment by kemar-art** [comment] 2023-01-11 13:28
> Hi here is the errors from the console
> 
> bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1 Uncaught TypeError: Cannot read properties of undefined (reading 'headers') at 7700 (bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:5283) at n (manifest.js?id=05687c4416821174765a9620f9e50c4f:1:147) at bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:26019 at n.O (manifest.js?id=05687c4416821174765a9620f9e50c4f:1:429) at bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:26039 at o (manifest.js?id=05687c4416821174765a9620f9e50c4f:1:3794) at bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:63 7700 @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1 n @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1 n.O @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1 o @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1 lang-loader.min.js:1 GET http://127.0.0.1:8000/lang/en.json 404 (Not Found) (anonymous) @ lang-loader.min.js:1 value @ lang-loader.min.js:1 value @ lang-loader.min.js:1 t @ lang-loader.min.js:1 3680 @ lang-loader.min.js:1 n @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ lang-loader.min.js:1 o @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 setup.min.js:1 (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}] setup.min.js:1 (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}] setup.min.js:1 {…} setup.min.js:1 {…} setup.min.js:1 {…} setup.min.js:1 {…} setup.min.js:1 {…} setup.min.js:1 {…} setup.min.js:1 {…} vendor.js?id=55a43eead10988a220735a7e6c14f715:2 ReferenceError: nsHttpClient is not defined at s.checkDatabase (setup.min.js:1:133221) at s.validate (setup.min.js:1:132839) at click (setup.min.js:1:135511) at $n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2556498) at s.n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2544141) at $n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2556498) at t.$emit (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2576374) at click (eval at Ul (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2637360), :3:124) at $n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2556498) at HTMLDivElement.n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2544141)



@Blair2004  @leonidas79 

I had that issue when I was installing this software locally and in Cpanel. what I had to do was to go in the database.php file and make a configuration. engine was equal to null when I changed it to  'InnoDB ROW_FORMAT=DYNAMIC' then I was able to install nexopos. 

 'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => env( 'DB_PREFIX', '' ),
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

**Comment by Blair2004** [comment] 2023-01-11 14:49
> > Hi here is the errors from the console
> > bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1 Uncaught TypeError: Cannot read properties of undefined (reading 'headers') at 7700 (bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:5283) at n (manifest.js?id=05687c4416821174765a9620f9e50c4f:1:147) at bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:26019 at n.O (manifest.js?id=05687c4416821174765a9620f9e50c4f:1:429) at bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:26039 at o (manifest.js?id=05687c4416821174765a9620f9e50c4f:1:3794) at bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1:63 7700 @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1 n @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1 n.O @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1 o @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ bootstrap.js?id=b8873b3c1f5d7dd5f16595a1f52a91d7:1 lang-loader.min.js:1 GET http://127.0.0.1:8000/lang/en.json 404 (Not Found) (anonymous) @ lang-loader.min.js:1 value @ lang-loader.min.js:1 value @ lang-loader.min.js:1 t @ lang-loader.min.js:1 3680 @ lang-loader.min.js:1 n @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ lang-loader.min.js:1 o @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 (anonymous) @ manifest.js?id=05687c4416821174765a9620f9e50c4f:1 setup.min.js:1 (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}] setup.min.js:1 (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}] setup.min.js:1 {…} setup.min.js:1 {…} setup.min.js:1 {…} setup.min.js:1 {…} setup.min.js:1 {…} setup.min.js:1 {…} setup.min.js:1 {…} vendor.js?id=55a43eead10988a220735a7e6c14f715:2 ReferenceError: nsHttpClient is not defined at s.checkDatabase (setup.min.js:1:133221) at s.validate (setup.min.js:1:132839) at click (setup.min.js:1:135511) at $n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2556498) at s.n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2544141) at $n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2556498) at t.$emit (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2576374) at click (eval at Ul (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2637360), :3:124) at $n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2556498) at HTMLDivElement.n (vendor.js?id=55a43eead10988a220735a7e6c14f715:2:2544141)
> 
> @Blair2004 @leonidas79
> 
> I had that issue when I was installing this software locally and in Cpanel. what I had to do was to go in the database.php file and make a configuration. engine was equal to null when I changed it to 'InnoDB ROW_FORMAT=DYNAMIC' then I was able to install nexopos.
> 
> 'mysql' => [ 'driver' => 'mysql', 'url' => env('DATABASE_URL'), 'host' => env('DB_HOST', '127.0.0.1'), 'port' => env('DB_PORT', '3306'), 'database' => env('DB_DATABASE', 'forge'), 'username' => env('DB_USERNAME', 'forge'), 'password' => env('DB_PASSWORD', ''), 'unix_socket' => env('DB_SOCKET', ''), 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => env( 'DB_PREFIX', '' ), 'prefix_indexes' => true, 'strict' => true, 'engine' => 'InnoDB ROW_FORMAT=DYNAMIC', 'options' => extension_loaded('pdo_mysql') ? array_filter([ PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'), ]) : [], ],

The issue was fixed by changing an implementation of "axios" we released an update already.
